# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Total_Metas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_ud', models.CharField(blank=True, max_length=500, null=True, verbose_name='Total de Unidade Demonstrativa')),
                ('total_um', models.CharField(blank=True, max_length=500, null=True, verbose_name='Total de Unidade Multiplicadora')),
                ('total_dc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Total de Dia de Campo')),
                ('total_prod', models.CharField(blank=True, max_length=500, null=True, verbose_name='Total de Produtores')),
                ('total_atec', models.CharField(blank=True, max_length=500, null=True, verbose_name='Total de ATECs')),
            ],
        ),
        migrations.CreateModel(
            name='Total_Metas_Bahia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bahia_total_ud', models.CharField(blank=True, max_length=500, null=True, verbose_name='Total de Unidade Demonstrativa')),
                ('bahia_total_um', models.CharField(blank=True, max_length=500, null=True, verbose_name='Total de Unidade Multiplicadora')),
                ('bahia_total_dc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Total de Dia de Campo')),
                ('bahia_total_prod', models.CharField(blank=True, max_length=500, null=True, verbose_name='Total de Produtores')),
                ('bahia_total_atec', models.CharField(blank=True, max_length=500, null=True, verbose_name='Total de ATECs')),
            ],
        ),
        migrations.CreateModel(
            name='Total_Metas_MatoGrosso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matogrosso_total_ud', models.CharField(blank=True, max_length=500, null=True, verbose_name='Total de Unidade Demonstrativa')),
                ('matogrosso_total_um', models.CharField(blank=True, max_length=500, null=True, verbose_name='Total de Unidade Multiplicadora')),
                ('matogrosso_total_dc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Total de Dia de Campo')),
                ('matogrosso_total_prod', models.CharField(blank=True, max_length=500, null=True, verbose_name='Total de Produtores')),
                ('matogrosso_total_atec', models.CharField(blank=True, max_length=500, null=True, verbose_name='Total de ATECs')),
            ],
        ),
        migrations.CreateModel(
            name='Total_Metas_MinasGerais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minasgerais_total_ud', models.CharField(blank=True, max_length=500, null=True, verbose_name='Total de Unidade Demonstrativa')),
                ('minasgerais_total_um', models.CharField(blank=True, max_length=500, null=True, verbose_name='Total de Unidade Multiplicadora')),
                ('minasgerais_total_dc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Total de Dia de Campo')),
                ('minasgerais_total_prod', models.CharField(blank=True, max_length=500, null=True, verbose_name='Total de Produtores')),
                ('minasgerais_total_atec', models.CharField(blank=True, max_length=500, null=True, verbose_name='Total de ATECs')),
            ],
        ),
        migrations.CreateModel(
            name='Total_Metas_Para',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para_total_ud', models.CharField(blank=True, max_length=500, null=True, verbose_name='Total de Unidade Demonstrativa')),
                ('para_total_um', models.CharField(blank=True, max_length=500, null=True, verbose_name='Total de Unidade Multiplicadora')),
                ('para_total_dc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Total de Dia de Campo')),
                ('para_total_prod', models.CharField(blank=True, max_length=500, null=True, verbose_name='Total de Produtores')),
                ('para_total_atec', models.CharField(blank=True, max_length=500, null=True, verbose_name='Total de ATECs')),
            ],
        ),
        migrations.CreateModel(
            name='Total_Metas_Parana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parana_total_ud', models.CharField(blank=True, max_length=500, null=True, verbose_name='Total de Unidade Demonstrativa')),
                ('parana_total_um', models.CharField(blank=True, max_length=500, null=True, verbose_name='Total de Unidade Multiplicadora')),
                ('parana_total_dc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Total de Dia de Campo')),
                ('parana_total_prod', models.CharField(blank=True, max_length=500, null=True, verbose_name='Total de Produtores')),
                ('parana_total_atec', models.CharField(blank=True, max_length=500, null=True, verbose_name='Total de ATECs')),
            ],
        ),
        migrations.CreateModel(
            name='Total_Metas_RioGrandeSul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riograndesul_total_ud', models.CharField(blank=True, max_length=500, null=True, verbose_name='Total de Unidade Demonstrativa')),
                ('riograndesul_total_um', models.CharField(blank=True, max_length=500, null=True, verbose_name='Total de Unidade Multiplicadora')),
                ('riograndesul_total_dc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Total de Dia de Campo')),
                ('riograndesul_total_prod', models.CharField(blank=True, max_length=500, null=True, verbose_name='Total de Produtores')),
                ('riograndesul_total_atec', models.CharField(blank=True, max_length=500, null=True, verbose_name='Total de ATECs')),
            ],
        ),
        migrations.CreateModel(
            name='Total_Metas_Rondonia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rondonia_total_ud', models.CharField(blank=True, max_length=500, null=True, verbose_name='Total de Unidade Demonstrativa')),
                ('rondonia_total_um', models.CharField(blank=True, max_length=500, null=True, verbose_name='Total de Unidade Multiplicadora')),
                ('rondonia_total_dc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Total de Dia de Campo')),
                ('rondonia_total_prod', models.CharField(blank=True, max_length=500, null=True, verbose_name='Total de Produtores')),
                ('rondonia_total_atec', models.CharField(blank=True, max_length=500, null=True, verbose_name='Total de ATECs')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=500, null=True, verbose_name='Nome Completo')),
                ('email', models.CharField(blank=True, max_length=500, null=True, verbose_name='E-mail')),
                ('senha', models.CharField(blank=True, max_length=500, null=True, verbose_name='Senha')),
            ],
        ),
    ]
