# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_new', models.IntegerField(blank=True, null=True, verbose_name='Chave da noticia')),
                ('data_create', models.CharField(blank=True, max_length=500, null=True, verbose_name='Data da noticia')),
                ('titulo', models.CharField(blank=True, max_length=500, null=True, verbose_name='Titulo')),
                ('chamada', models.CharField(blank=True, max_length=500, null=True, verbose_name='Chamada')),
                ('conteudo', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Conteudo')),
                ('image_link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Link da imagem')),
                ('estado', models.CharField(blank=True, max_length=500, null=True, verbose_name='Estado da materia')),
                ('destaque', models.CharField(blank=True, max_length=500, null=True, verbose_name='Destaque')),
            ],
        ),
    ]
