# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0002_noticias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usernoticias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=500, null=True, verbose_name='Nome Completo')),
                ('email', models.CharField(blank=True, max_length=500, null=True, verbose_name='E-mail')),
                ('verificado', models.CharField(blank=True, max_length=500, null=True, verbose_name='adicionado')),
            ],
        ),
    ]
