# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0003_usernoticias'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='data_post',
            field=models.DateTimeField(auto_now=True, verbose_name='Data da noticiapost'),
        ),
    ]
