# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0004_noticias_data_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='data_post',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data da noticia post'),
        ),
    ]
