# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0005_auto_20171120_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGestor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_user', models.CharField(blank=True, max_length=500, null=True, verbose_name='Nome Completo do usuario')),
                ('senha_user', models.CharField(blank=True, max_length=500, null=True, verbose_name='Senha')),
                ('email_usuario', models.CharField(blank=True, max_length=500, null=True, verbose_name='E-mail')),
                ('img_profile', models.CharField(blank=True, max_length=500, null=True, verbose_name='Link imagem login')),
            ],
        ),
    ]
