# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0006_usergestor'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergestor',
            name='perfil_user',
            field=models.CharField(blank=True, choices=[(b'101010', b'Administrador'), (b'202020', b'Atualizador de metas'), (b'303030', b'Criador de noticias')], default=b'', max_length=50, null=True, verbose_name='Perfil do usuario'),
        ),
    ]
