# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-25 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0008_delete_usergestor'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetasGerais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade_demonstrativa', models.IntegerField(blank=True, null=True, verbose_name='Unidade Demonstrativa')),
                ('unidade_multiplicadora', models.IntegerField(blank=True, null=True, verbose_name='Unidade Multiplicadora')),
                ('dia_campo', models.IntegerField(blank=True, null=True, verbose_name='Dia de Campo')),
                ('produtores_capacitados', models.IntegerField(blank=True, null=True, verbose_name='Produtores Capacitados')),
                ('atecs_treinados', models.IntegerField(blank=True, null=True, verbose_name='ATECs Treinados')),
                ('ativado', models.BooleanField(default=False, verbose_name='Dados ativados')),
            ],
        ),
        migrations.DeleteModel(
            name='Usernoticias',
        ),
    ]
