# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-25 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0009_auto_20180125_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metasgerais',
            name='ativado',
        ),
    ]
