# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-26 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0010_remove_metasgerais_ativado'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetasBA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade_demonstrativa', models.IntegerField(blank=True, null=True, verbose_name='Unidade Demonstrativa')),
                ('unidade_multiplicadora', models.IntegerField(blank=True, null=True, verbose_name='Unidade Multiplicadora')),
                ('dia_campo', models.IntegerField(blank=True, null=True, verbose_name='Dia de Campo')),
                ('produtores_capacitados', models.IntegerField(blank=True, null=True, verbose_name='Produtores Capacitados')),
                ('atecs_treinados', models.IntegerField(blank=True, null=True, verbose_name='ATECs Treinados')),
            ],
        ),
        migrations.CreateModel(
            name='MetasMG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade_demonstrativa', models.IntegerField(blank=True, null=True, verbose_name='Unidade Demonstrativa')),
                ('unidade_multiplicadora', models.IntegerField(blank=True, null=True, verbose_name='Unidade Multiplicadora')),
                ('dia_campo', models.IntegerField(blank=True, null=True, verbose_name='Dia de Campo')),
                ('produtores_capacitados', models.IntegerField(blank=True, null=True, verbose_name='Produtores Capacitados')),
                ('atecs_treinados', models.IntegerField(blank=True, null=True, verbose_name='ATECs Treinados')),
            ],
        ),
        migrations.CreateModel(
            name='MetasMT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade_demonstrativa', models.IntegerField(blank=True, null=True, verbose_name='Unidade Demonstrativa')),
                ('unidade_multiplicadora', models.IntegerField(blank=True, null=True, verbose_name='Unidade Multiplicadora')),
                ('dia_campo', models.IntegerField(blank=True, null=True, verbose_name='Dia de Campo')),
                ('produtores_capacitados', models.IntegerField(blank=True, null=True, verbose_name='Produtores Capacitados')),
                ('atecs_treinados', models.IntegerField(blank=True, null=True, verbose_name='ATECs Treinados')),
            ],
        ),
        migrations.CreateModel(
            name='MetasPA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade_demonstrativa', models.IntegerField(blank=True, null=True, verbose_name='Unidade Demonstrativa')),
                ('unidade_multiplicadora', models.IntegerField(blank=True, null=True, verbose_name='Unidade Multiplicadora')),
                ('dia_campo', models.IntegerField(blank=True, null=True, verbose_name='Dia de Campo')),
                ('produtores_capacitados', models.IntegerField(blank=True, null=True, verbose_name='Produtores Capacitados')),
                ('atecs_treinados', models.IntegerField(blank=True, null=True, verbose_name='ATECs Treinados')),
            ],
        ),
        migrations.CreateModel(
            name='MetasPR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade_demonstrativa', models.IntegerField(blank=True, null=True, verbose_name='Unidade Demonstrativa')),
                ('unidade_multiplicadora', models.IntegerField(blank=True, null=True, verbose_name='Unidade Multiplicadora')),
                ('dia_campo', models.IntegerField(blank=True, null=True, verbose_name='Dia de Campo')),
                ('produtores_capacitados', models.IntegerField(blank=True, null=True, verbose_name='Produtores Capacitados')),
                ('atecs_treinados', models.IntegerField(blank=True, null=True, verbose_name='ATECs Treinados')),
            ],
        ),
        migrations.CreateModel(
            name='MetasRO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade_demonstrativa', models.IntegerField(blank=True, null=True, verbose_name='Unidade Demonstrativa')),
                ('unidade_multiplicadora', models.IntegerField(blank=True, null=True, verbose_name='Unidade Multiplicadora')),
                ('dia_campo', models.IntegerField(blank=True, null=True, verbose_name='Dia de Campo')),
                ('produtores_capacitados', models.IntegerField(blank=True, null=True, verbose_name='Produtores Capacitados')),
                ('atecs_treinados', models.IntegerField(blank=True, null=True, verbose_name='ATECs Treinados')),
            ],
        ),
        migrations.CreateModel(
            name='MetasRS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade_demonstrativa', models.IntegerField(blank=True, null=True, verbose_name='Unidade Demonstrativa')),
                ('unidade_multiplicadora', models.IntegerField(blank=True, null=True, verbose_name='Unidade Multiplicadora')),
                ('dia_campo', models.IntegerField(blank=True, null=True, verbose_name='Dia de Campo')),
                ('produtores_capacitados', models.IntegerField(blank=True, null=True, verbose_name='Produtores Capacitados')),
                ('atecs_treinados', models.IntegerField(blank=True, null=True, verbose_name='ATECs Treinados')),
            ],
        ),
    ]
