# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-27 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0011_metasba_metasmg_metasmt_metaspa_metaspr_metasro_metasrs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Total_Metas',
        ),
        migrations.DeleteModel(
            name='Total_Metas_Bahia',
        ),
        migrations.DeleteModel(
            name='Total_Metas_MatoGrosso',
        ),
        migrations.DeleteModel(
            name='Total_Metas_MinasGerais',
        ),
        migrations.DeleteModel(
            name='Total_Metas_Para',
        ),
        migrations.DeleteModel(
            name='Total_Metas_Parana',
        ),
        migrations.DeleteModel(
            name='Total_Metas_RioGrandeSul',
        ),
        migrations.DeleteModel(
            name='Total_Metas_Rondonia',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
