# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-05 11:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0012_auto_20180127_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticiasProjeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_home', models.NullBooleanField(default=False)),
                ('titulo', models.CharField(blank=True, max_length=500, verbose_name='T\xedtulo da not\xedcias')),
                ('chamada', models.CharField(blank=True, max_length=500, verbose_name='Chamada da not\xedcias')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_publicacao', models.DateField(default=datetime.date.today, verbose_name='Data da publica\xe7\xe3o')),
                ('img_noticia', models.CharField(blank=True, max_length=1000, verbose_name='Imagem da not\xedcias')),
                ('img_credito', models.CharField(blank=True, max_length=1000, verbose_name='Creditos da imagens')),
                ('album_one', models.CharField(blank=True, max_length=1000, verbose_name='\xc1lbum imagem')),
                ('album_two', models.CharField(blank=True, max_length=1000, verbose_name='\xc1lbum imagem')),
                ('album_three', models.CharField(blank=True, max_length=1000, verbose_name='\xc1lbum imagem')),
                ('album_four', models.CharField(blank=True, max_length=1000, verbose_name='\xc1lbum imagem')),
                ('album_five', models.CharField(blank=True, max_length=1000, verbose_name='\xc1lbum imagem')),
                ('conteudo', models.TextField(blank=True, max_length=10000, verbose_name='Conte\xfado da not\xedcias')),
                ('video', models.CharField(blank=True, max_length=1000, verbose_name='V\xeddeo')),
                ('video_descricao', models.CharField(blank=True, max_length=1000, verbose_name='Descri\xe7\xe3o do v\xeddeo')),
                ('Estado', models.CharField(blank=True, max_length=1000, verbose_name='Estado')),
            ],
        ),
    ]
