# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-05 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0013_noticiasprojeto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticiasprojeto',
            name='Estado',
        ),
        migrations.AddField(
            model_name='noticiasprojeto',
            name='album_six',
            field=models.CharField(blank=True, max_length=1000, verbose_name='\xc1lbum imagem'),
        ),
        migrations.AddField(
            model_name='noticiasprojeto',
            name='estado',
            field=models.CharField(blank=True, choices=[(b'PA', b'Par\xc3\xa1'), (b'MT', b'Mato Grosso'), (b'RO', b'Rond\xc3\xb4nia'), (b'RS', b'Rio Grande do Sul'), (b'BA', b'Bahia'), (b'PR', b'Paran\xc3\xa1'), (b'MG', b'Minas Gerais'), (b'DF', b'Bras\xc3\xadlia')], default=b'DF', max_length=150, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='noticiasprojeto',
            name='chamada',
            field=models.CharField(blank=True, max_length=500, verbose_name='Chamada da not\xedcia'),
        ),
        migrations.AlterField(
            model_name='noticiasprojeto',
            name='titulo',
            field=models.CharField(blank=True, max_length=500, verbose_name='T\xedtulo da not\xedcia'),
        ),
    ]
