# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-06 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0014_auto_20180205_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incluido', models.NullBooleanField(default=False)),
                ('nome_user', models.CharField(blank=True, max_length=500, verbose_name='T\xedtulo da not\xedcia')),
                ('email_user', models.CharField(blank=True, max_length=500, verbose_name='Chamada da not\xedcia')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
