# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-19 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0015_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depoimentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_create', models.CharField(blank=True, max_length=500, null=True, verbose_name='Data da noticia')),
                ('titulo', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Titulo')),
                ('descricao', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Conteudo')),
                ('embed_link', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Link do Embrad do video')),
                ('link_img', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Link da imagem')),
            ],
        ),
    ]
