# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-19 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0016_depoimentos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depoimentos',
            name='data_create',
        ),
        migrations.AddField(
            model_name='depoimentos',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
